# Site settings
title: Clifford Robinson | Digital Media
description: Hello, I'm Clifford, A JavaScript Developer and also a Digital Media Student!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Clifford Robinson
user_description: John Johnson once said, First, Solve the problem. Then, Write the code. I believe this is true when it comes to describing my goals in life because I want to be a freelance developer when I grow up and this will happen alot when I am working on projects and more. 
Currently, I am a high school freshman and I am taking a variety of classes including Spanish, Construction, and Digital Media. My favorite class is Construction because I get to work hands-on with tools and more. I hope this class will teach me to be able to build and create things with my hands. Someday, Id like to attend a 4 year college at UCR. Eventually, I would like to become a Freelance Developer.  Right now, I am focusing on improving myself by Coding Skills. 
My hobbies include making websites to improve my website making skills.
user_title: Student Developer
email: bean@wokser.tech
twitter_username: MrBeanGuy
github_username:  MrBeanGuy
# gplus_username:  lorem_ipsum

# Google-analytics
# google-analytics:
# id: ""

exclude: ['package.json', 'src' , 'node_modules']
